### ISSUE TITLE
🐛 Bug Report: Unable to use .community domains as custom domains in firefox

### ISSUE THREAD

**Issue by MaximumMaxxx** [appwrite/console#474] opened 2023-07-05 21:51 UTC
### 👟 Reproduction steps

- Go to any project and try to add a custom domain
- Enter a domain ending with .community

### 👍 Expected behavior

The form should accept .community domains and move on to the next step

![image](https://github.com/appwrite/console/assets/77695343/9bd23ae8-9f39-4179-a9f0-2a3ec1705cfd)

### 👎 Actual Behavior

You get a "Must be a valid domain error"

![image](https://github.com/appwrite/console/assets/77695343/0a06fe50-48a2-480f-86c7-ef06b7dbc8fe)

Note that it is possible to bypass this error by changing the validation pattern on the form
![image](https://github.com/appwrite/console/assets/77695343/df32b55b-e24f-49b3-8a84-d284394ca7ab)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by MaximumMaxxx** [comment] 2023-07-05 21:52
Also just noticed that this issue only seems to happen in ff. Chrome works as expected

**Comment by MaximumMaxxx** [comment] 2023-07-05 21:53
Relevant discord messages too:
https://discord.com/channels/564160730845151244/1102936099745177700/1125937233636114432
https://discord.com/channels/564160730845151244/1102936099745177700/1123339779627556986

**Comment by MaximumMaxxx** [comment] 2023-07-05 22:25
I think I've narrowed down the problem to this part of the regex
```
^(?!-)[A-Za-z0-9-]+([\-\.]{1}[a-z0-9]+)*\.[A-Za-z]{2,6}$
                                                     ^
```

Any tld longer than 6 characters doesn't get matched. Which works fine except that some tlds are longer than 6 characters as seen with `.contractors`. The longest is in fact 24 (XN--VERMGENSBERATUNG-PWB), although it could theorertically be up to 63 characters

![image](https://media.discordapp.net/attachments/1102936099745177700/1126275152942993459/image.png)


![image](https://media.discordapp.net/attachments/1102936099745177700/1126275418668933231/image.png)


The solution would be to bump the limit to either 24 or 63
```
^(?!-)[A-Za-z0-9-]+([\-\.]{1}[a-z0-9]+)*\.[A-Za-z]{2,24}$
                                                     ^
```

**Comment by stnguyen90** [comment] 2023-07-28 00:49
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/5273

**Closed by stnguyen90** 2023-07-28 00:49 UTC
Labels: bug
