### ISSUE TITLE
🐛 Bug Report: Dashboard does not show the info on user, database and storage

### ISSUE THREAD

**Issue by MaddPenguin** [appwrite/console#196] opened 2022-11-25 07:06 UTC
### 👟 Reproduction steps

The dash does show all the info on a newly created projects but always ends up showing 0 for all info on the next day.
So far this issue has affected all my Appwrite instances, local or cloud.

![Screenshot from 2022-11-25 14-42-33](https://user-images.githubusercontent.com/60058928/203917170-0c4736c0-ade9-4c16-9106-a5362127ea03.png)

<details>
  <summary>docker logs appwrite</summary>  

```[Error] Timestamp: 2022-11-25T06:50:15+00:00
[Error] Method: GET
[Error] URL: /v1/account
[Error] Type: Appwrite\Extend\Exception
[Error] Message: Project with the requested ID could not be found. Please check the value of the X-Appwrite-Project header to ensure the correct project ID is being used.
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 143
[Error] Timestamp: 2022-11-25T06:50:26+00:00
[Error] Method: GET
[Error] URL: /v1/account
[Error] Type: Appwrite\Extend\Exception
[Error] Message: Project with the requested ID could not be found. Please check the value of the X-Appwrite-Project header to ensure the correct project ID is being used.
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 143
[2022-11-25 06:50:29 *15.4]     NOTICE  ProcessFactory::finish() (ERRNO 1004): send 1970 bytes failed, because session#35 is closed
[2022-11-25 06:50:29 *15.4]     NOTICE  ProcessFactory::end() (ERRNO 1005): session#35 is closed
[2022-11-25 06:50:52 *16.5]     NOTICE  ProcessFactory::finish() (ERRNO 1004): send 9793 bytes failed, because session#36 is closed
[2022-11-25 06:50:52 *16.5]     NOTICE  ProcessFactory::end() (ERRNO 1005): session#36 is closed
[Error] Timestamp: 2022-11-25T06:51:04+00:00
[Error] Method: GET
[Error] URL: /v1/account
[Error] Type: Appwrite\Extend\Exception
[Error] Message: Project with the requested ID could not be found. Please check the value of the X-Appwrite-Project header to ensure the correct project ID is being used.
[Error] File: /usr/src/code/app/controllers/general.php
```
</details>

<details>
  <summary>appwrite doctor</summary>

```
👩‍⚕️ Running Appwrite Doctor for version 1.1.2 ...

Checking for production best practices...
🟢 Hostname has a public suffix (mydomain)
🟢 CNAME target has a public suffix (mydomain)
🟢 Using a unique secret key for encryption
🟢 App environment is set for production
🟢 Abuse protection is enabled
🟢 Console access limits are enabled
🔴 HTTPS force option is disabled
🔴 Logging adapter is disabled

Checking connectivity...
Database............connected 👍
Queue...............connected 👍
Cache...............connected 👍
SMTP................connected 👍
StatsD..............connected 👍
InfluxDB............connected 👍

Checking volumes...
🟢 Uploads Volume is readable
🟢 Uploads Volume is writeable
🟢 Cache Volume is readable
🟢 Cache Volume is writeable
🟢 Config Volume is readable
🟢 Config Volume is writeable
🟢 Certs Volume is readable
🟢 Certs Volume is writeable

Checking disk space usage...
🟢 Uploads Volume has 43.10GB free space (17.54% used)
🟢 Cache Volume has 43.10GB free space (17.54% used)
🟢 Config Volume has 43.10GB free space (17.54% used)
🟢 Certs Volume has 43.10GB free space (17.54% used)
```
</details>

### 👍 Expected behavior

For the dash to show all the info

### 👎 Actual Behavior

Dash ends up showing 0 info

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite v1.1.1 & v.1.1.2
Linode instance - archlinux, ubuntu 22.04
Local docker on arch

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-11-26 07:12
@MaddPenguin thanks for raising this issue! 🙏 Some questions:

1. Is this from a clean install or did you upgrade from a previous version?
2. What are the logs for the `appwrite-usage` container?

**Comment by MaddPenguin** [comment] 2022-11-26 07:51
1. Clean install
2. No error in appwrite -usage

```
[26-11-2022 07:46:43] Aggregating Timeseries Usage data every 30 seconds
[26-11-2022 07:46:43] Aggregation took 0.18834495544434 seconds
[26-11-2022 07:47:13] Aggregating Timeseries Usage data every 30 seconds
[26-11-2022 07:47:13] Aggregation took 0.21986293792725 seconds
[26-11-2022 07:47:43] Aggregating Timeseries Usage data every 30 seconds
[26-11-2022 07:47:44] Aggregation took 0.20194101333618 seconds
[26-11-2022 07:48:14] Aggregating Timeseries Usage data every 30 seconds
[26-11-2022 07:48:14] Aggregation took 0.20684194564819 seconds
[26-11-2022 07:48:44] Aggregating Timeseries Usage data every 30 seconds
[26-11-2022 07:48:44] Aggregation took 0.19576692581177 seconds
[26-11-2022 07:49:14] Aggregating Timeseries Usage data every 30 seconds
[26-11-2022 07:49:14] Aggregation took 0.21519804000854 seconds
[26-11-2022 07:49:44] Aggregating Timeseries Usage data every 30 seconds
[26-11-2022 07:49:44] Aggregation took 0.19998693466187 seconds
[26-11-2022 07:50:14] Aggregating Timeseries Usage data every 30 seconds
[26-11-2022 07:50:15] Aggregation took 0.22066211700439 seconds
```

**Comment by MaddPenguin** [comment] 2022-12-02 07:40
@stnguyen90 This is my appwrite-usage logs now. Issue still persist. docker-logs appwrite still the same as the old one. No logs in appwrite-worker-databases

```[01-12-2022 11:03:03] Aggregation took 0.51719307899475 seconds
[01-12-2022 11:03:33] Aggregating Timeseries Usage data every 30 seconds
[PDO] MySQL connection restarted
Failed: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'value' at row 1
#0 /usr/src/code/src/Appwrite/Extend/PDOStatement.php(88): PDOStatement->execute(NULL)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(722): Appwrite\Extend\PDOStatement->execute()
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1412): Utopia\Database\Adapter\MariaDB->updateDocument('stats', Object(Utopia\Database\Document))
#3 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(427): Utopia\Database\Database->updateDocument(Object(Utopia\Database\Document), '4b413054c0cfe4d...', Object(Utopia\Database\Document))
#4 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(503): Appwrite\Usage\Calculators\TimeSeries->createOrUpdateMetric('1', '2022-12-01T00:0...', '1d', 'files.$637efd79...', -85922, 0)
#5 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(528): Appwrite\Usage\Calculators\TimeSeries->syncFromInfluxDB('files.$bucketId...', Array, Array)
#6 /usr/src/code/app/tasks/usage.php(132): Appwrite\Usage\Calculators\TimeSeries->collect()
#7 /usr/src/code/vendor/utopia-php/cli/src/CLI/Console.php(208): {closure}()
#8 /usr/src/code/app/tasks/usage.php(137): Utopia\CLI\Console::loop(Object(Closure), 30)
#9 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}()
#10 /usr/src/code/app/cli.php(32): Utopia\CLI\CLI->run()
#11 {main}
[PDO] MySQL connection restarted
Failed: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'value' at row 1
#0 /usr/src/code/src/Appwrite/Extend/PDOStatement.php(88): PDOStatement->execute(NULL)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(722): Appwrite\Extend\PDOStatement->execute()
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1412): Utopia\Database\Adapter\MariaDB->updateDocument('stats', Object(Utopia\Database\Document))
#3 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(427): Utopia\Database\Database->updateDocument(Object(Utopia\Database\Document), 'a3dd0d087b20f3c...', Object(Utopia\Database\Document))
#4 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(503): Appwrite\Usage\Calculators\TimeSeries->createOrUpdateMetric('1', '2022-12-01T00:0...', '1d', 'files.637efd79b...', -85922, 0)
#5 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(528): Appwrite\Usage\Calculators\TimeSeries->syncFromInfluxDB('files.bucketId....', Array, Array)
#6 /usr/src/code/app/tasks/usage.php(132): Appwrite\Usage\Calculators\TimeSeries->collect()
#7 /usr/src/code/vendor/utopia-php/cli/src/CLI/Console.php(208): {closure}()
#8 /usr/src/code/app/tasks/usage.php(137): Utopia\CLI\Console::loop(Object(Closure), 30)
#9 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}()
#10 /usr/src/code/app/cli.php(32): Utopia\CLI\CLI->run()
#11 {main}
[01-12-2022 11:03:34] Aggregation took 0.49070191383362 seconds
[01-12-2022 11:04:04] Aggregating Timeseries Usage data every 30 seconds
[PDO] MySQL connection restarted
Failed: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'value' at row 1
#0 /usr/src/code/src/Appwrite/Extend/PDOStatement.php(88): PDOStatement->execute(NULL)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(722): Appwrite\Extend\PDOStatement->execute()
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1412): Utopia\Database\Adapter\MariaDB->updateDocument('stats', Object(Utopia\Database\Document))
#3 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(427): Utopia\Database\Database->updateDocument(Object(Utopia\Database\Document), '4b413054c0cfe4d...', Object(Utopia\Database\Document))
#4 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(503): Appwrite\Usage\Calculators\TimeSeries->createOrUpdateMetric('1', '2022-12-01T00:0...', '1d', 'files.$637efd79...', -85922, 0)
#5 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(528): Appwrite\Usage\Calculators\TimeSeries->syncFromInfluxDB('files.$bucketId...', Array, Array)
#6 /usr/src/code/app/tasks/usage.php(132): Appwrite\Usage\Calculators\TimeSeries->collect()
#7 /usr/src/code/vendor/utopia-php/cli/src/CLI/Console.php(208): {closure}()
#8 /usr/src/code/app/tasks/usage.php(137): Utopia\CLI\Console::loop(Object(Closure), 30)
#9 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}()
#10 /usr/src/code/app/cli.php(32): Utopia\CLI\CLI->run()
#11 {main}
[PDO] MySQL connection restarted
Failed: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'value' at row 1
#0 /usr/src/code/src/Appwrite/Extend/PDOStatement.php(88): PDOStatement->execute(NULL)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(722): Appwrite\Extend\PDOStatement->execute()```

**Comment by stnguyen90** [comment] 2022-12-08 23:07
@MaddPenguin this looks like a duplicate of https://github.com/appwrite/appwrite/issues/4751. If so, would you please close this and 👍🏼 the other issue?

**Closed** 2022-12-09 04:53 UTC
Labels: bug
