### ISSUE TITLE
🐛 Bug Report: Boolean attributes in collections are set to undefined when false is default

### ISSUE THREAD

**Issue by sagodi97** [appwrite/console#362] opened 2023-03-23 16:25 UTC
### 👟 Reproduction steps

Hi 👋🏽 I know this is a really minor detail, but it bugged me today, so I figured I might as well report it.

1. In a Collection, add a new attribute
2. Give it a key and set the "Attribute type" to `Boolean`
3. Set "Default value" to `False`
4. Save

### 👍 Expected behavior

The default value should be `false`

### 👎 Actual Behavior

It always set to `undefined` unless a default of `True` is selected

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

* Appwrite 1.2.1 running on VPS (Ubuntu)
* Using Web SDK

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by sagodi97** [comment] 2023-03-23 16:27
https://github.com/appwrite/console/blob/3768a323a7af8dbad3142d46d3ea43d6d750e5fe/src/routes/console/project-%5Bproject%5D/databases/database-%5Bdatabase%5D/collection-%5Bcollection%5D/attributes/boolean.svelte#L16

I believe it should be instead:
```javascript
typeof data.default === "boolean" ? data.default : undefined, 
```

**Comment by stnguyen90** [comment] 2023-03-23 23:42
I can confirm that if the value is `false` it shows as `n/a`

<img width="838" alt="image" src="https://user-images.githubusercontent.com/1477010/227388050-0bed6acf-a3a2-4485-8e6f-25077a831eda.png">

**Comment by stnguyen90** [comment] 2023-03-23 23:48
@sagodi97, I think the issue you brought up is actually a duplicate of https://github.com/appwrite/appwrite/issues/4712. If so, would you please close this and 👍🏼 the other issue?

**Comment by sagodi97** [comment] 2023-03-24 06:38
Yup, thanks! My bad, I only looked in this repo's issues

**Closed** 2023-03-24 06:37 UTC
Labels: bug
