### ISSUE TITLE
🐛 Bug Report: Organization deletion does not work

### ISSUE THREAD

**Issue by docimin** [appwrite/console#1056] opened 2024-04-26 23:05 UTC
### 👟 Reproduction steps

Click the delete button to delete the organization under the /console/organization-[organizationId]/settings, it will show no modal.

### 👍 Expected behavior

Shows a modal to make sure that you want to delete the organization

### 👎 Actual Behavior

Doesn't show the modal to delete it, so the button will do nothing

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Applies to every environment using Appwrite 1.5.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-04-27 01:34
@docimin, thanks for creating this issue! 🙏

**Comment by stnguyen90** [comment] 2024-04-27 06:29
Duplicate of #1030

**Closed by stnguyen90** 2024-04-27 06:29 UTC
Labels: bug
