### ISSUE TITLE
🐛 Bug Report: Stripe calling home for unknown reasons

### ISSUE THREAD

**Issue by ttrinidad** [appwrite/console#1168] opened 2024-06-30 11:25 UTC
### 👟 Reproduction steps

Self-host Appwrite console constantly sends tracking to Stripe. It should NOT.

### 👍 Expected behavior

Not send stuff to other websites. Breach of privacy, and it's just stupid to send to Stripe when not even being used at all.
Not even include stripe if needed to avoid that.

### 👎 Actual Behavior

Sending metrics or whatever to Stripe

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

[Version 1.5.7](https://github.com/appwrite/appwrite/releases)
Installed through Coolify

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment] 2024-07-08 09:50
We do actually have a check for that in place here https://github.com/appwrite/console/blob/main/src/routes/console/%2Blayout.svelte#L243-L248 - I'll do some digging to see why its doing that on self-hosted 👍🏻

**Comment by TorstenDittmann** [comment] 2024-07-08 09:58
@ttrinidad I can't seem to find any evidence we are initializing stripe nor sending any requests on self-hosted 👍🏻 

Can you tell me where this is happening to you? 🙂

**Comment by TorstenDittmann** [comment] 2024-07-08 18:34
nevermind, just was able to reproduce it - this is definitely a bug and not intended!

**Comment by TorstenDittmann** [comment] 2024-07-08 18:53
Found the reason why I couldn't reproduce it at first. The fix for it got merged last month, but hasn't been released yet.

https://github.com/appwrite/console/pull/1111

It will be fixed once 1.5.8 is released 🙏🏻

**Closed** 2024-07-08 18:54 UTC
Labels: bug
